#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-script-interpreter
Version  : 1
Release  : 1
URL      : https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-script-interpreter/1.0/maven-script-interpreter-1.0-sources.jar
Source0  : https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-script-interpreter/1.0/maven-script-interpreter-1.0-sources.jar
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-script-interpreter/1.0/maven-script-interpreter-1.0.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-script-interpreter/1.0/maven-script-interpreter-1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maven-script-interpreter-data = %{version}-%{release}
Requires: mvn-maven-script-interpreter-license = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-maven-script-interpreter package.
Group: Data

%description data
data components for the mvn-maven-script-interpreter package.


%package license
Summary: license components for the mvn-maven-script-interpreter package.
Group: Default

%description license
license components for the mvn-maven-script-interpreter package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-maven-script-interpreter
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-maven-script-interpreter/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-maven-script-interpreter/NOTICE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-script-interpreter/1.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-script-interpreter/1.0/maven-script-interpreter-1.0-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-script-interpreter/1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-script-interpreter/1.0/maven-script-interpreter-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-script-interpreter/1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-script-interpreter/1.0/maven-script-interpreter-1.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-script-interpreter/1.0/maven-script-interpreter-1.0-sources.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-script-interpreter/1.0/maven-script-interpreter-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-script-interpreter/1.0/maven-script-interpreter-1.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-maven-script-interpreter/LICENSE
/usr/share/package-licenses/mvn-maven-script-interpreter/NOTICE
